// <auto-generated />
using System;
using API.SIGE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.SIGE.Migrations
{
    [DbContext(typeof(AppDbData))]
    [Migration("20260324142803_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.SIGE.Models.Caixilho", b =>
                {
                    b.Property<int>("IdCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCaixilho"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataLiberacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCaixilho")
                        .HasColumnType("text");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("Largura")
                        .HasColumnType("integer");

                    b.Property<bool>("Liberado")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCaixilho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ObraId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("PesoUnitario")
                        .HasColumnType("real");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("IdCaixilho");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("ObraId");

                    b.ToTable("Caixilho");
                });

            modelBuilder.Entity("SIGE.API.Models.FamiliaCaixilho", b =>
                {
                    b.Property<int>("IdFamiliaCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFamiliaCaixilho"));

                    b.Property<string>("DescricaoFamilia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PesoTotal")
                        .HasColumnType("integer");

                    b.HasKey("IdFamiliaCaixilho");

                    b.ToTable("FamiliaCaixilho");
                });

            modelBuilder.Entity("SIGE.API.Models.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObra"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Construtora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("ImagemObraPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("PercentualConclusao")
                        .HasColumnType("real");

                    b.Property<float>("PesoFinal")
                        .HasColumnType("real");

                    b.Property<float>("PesoProduzido")
                        .HasColumnType("real");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("IdObra");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("SIGE.API.Models.Producao", b =>
                {
                    b.Property<int>("IdProducao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducao"));

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EhLiberado")
                        .HasColumnType("boolean");

                    b.Property<int>("FamiliaCaixilhoId")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeProducao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Produzido")
                        .HasColumnType("boolean");

                    b.HasKey("IdProducao");

                    b.HasIndex("FamiliaCaixilhoId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Producao");
                });

            modelBuilder.Entity("SIGE.API.Models.RelatorioProducao", b =>
                {
                    b.Property<int>("IdRelatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRelatorio"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRelatorio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EficienciaProducao")
                        .HasColumnType("real");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<float>("PesoTotalProduzido")
                        .HasColumnType("real");

                    b.Property<string>("StatusMeta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TempoMedioProducao")
                        .HasColumnType("real");

                    b.Property<int>("TotalCaixilhosProduzidos")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFamiliasProduzidas")
                        .HasColumnType("integer");

                    b.HasKey("IdRelatorio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RelatorioProducao");
                });

            modelBuilder.Entity("SIGE.API.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("NomeTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("SIGE.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Models.Caixilho", b =>
                {
                    b.HasOne("SIGE.API.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGE.API.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("SIGE.API.Models.Obra", b =>
                {
                    b.HasOne("SIGE.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGE.API.Models.Producao", b =>
                {
                    b.HasOne("SIGE.API.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("FamiliaCaixilhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGE.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGE.API.Models.RelatorioProducao", b =>
                {
                    b.HasOne("SIGE.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGE.API.Models.Usuario", b =>
                {
                    b.HasOne("SIGE.API.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
