// <auto-generated />
using System;
using API.SIGE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.SIGE.Migrations
{
    [DbContext(typeof(AppDbData))]
    partial class AppDbDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.SIGE.Model.Anexo", b =>
                {
                    b.Property<int>("IdAnexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnexo"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int?>("IdMedicao")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProducaoFamilia")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoAnexo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdAnexo");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdMedicao");

                    b.HasIndex("IdProducaoFamilia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Anexo");
                });

            modelBuilder.Entity("API.SIGE.Model.Caixilho", b =>
                {
                    b.Property<int>("IdCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCaixilho"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataLiberacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCaixilho")
                        .HasColumnType("text");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("Largura")
                        .HasColumnType("integer");

                    b.Property<bool>("Liberado")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCaixilho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ObraId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("PesoUnitario")
                        .HasColumnType("real");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("StatusProducao")
                        .HasColumnType("integer");

                    b.HasKey("IdCaixilho");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("ObraId");

                    b.ToTable("Caixilho");
                });

            modelBuilder.Entity("API.SIGE.Model.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("DescricaoCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCargo")
                        .HasColumnType("integer");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("TipoCargo", "IdEmpresa")
                        .IsUnique();

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("API.SIGE.Model.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("API.SIGE.Model.FamiliaCaixilho", b =>
                {
                    b.Property<int>("IdFamiliaCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFamiliaCaixilho"));

                    b.Property<string>("DescricaoFamilia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdObra")
                        .HasColumnType("integer");

                    b.Property<int>("PesoTotal")
                        .HasColumnType("integer");

                    b.Property<int>("StatusFamilia")
                        .HasColumnType("integer");

                    b.HasKey("IdFamiliaCaixilho");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdObra");

                    b.ToTable("FamiliaCaixilho");
                });

            modelBuilder.Entity("API.SIGE.Model.Medicao", b =>
                {
                    b.Property<int>("IdMedicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedicao"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEstimadaConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IdMedicao");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("Medicao");
                });

            modelBuilder.Entity("API.SIGE.Model.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int?>("IdObra")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioDestino")
                        .HasColumnType("integer");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TipoNotificacao")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("Notificacao");
                });

            modelBuilder.Entity("API.SIGE.Model.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObra"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Construtora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("ImagemObraPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("PercentualConclusao")
                        .HasColumnType("real");

                    b.Property<float>("PercentualMedicao")
                        .HasColumnType("real");

                    b.Property<float>("PercentualProducao")
                        .HasColumnType("real");

                    b.Property<float>("PesoFinal")
                        .HasColumnType("real");

                    b.Property<float>("PesoProduzido")
                        .HasColumnType("real");

                    b.Property<int>("StatusObra")
                        .HasColumnType("integer");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("IdObra");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("API.SIGE.Model.ProducaoFamilia", b =>
                {
                    b.Property<int>("IdProducaoFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducaoFamilia"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEstimadaConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IdProducaoFamilia");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("ProducaoFamilia");
                });

            modelBuilder.Entity("API.SIGE.Model.SolicitacaoCadastro", b =>
                {
                    b.Property<int>("IdSolicitacaoCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitacaoCadastro"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TelefoneResponsavel")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("IdSolicitacaoCadastro");

                    b.ToTable("SolicitacaoCadastro");
                });

            modelBuilder.Entity("API.SIGE.Model.SolicitacaoCliente", b =>
                {
                    b.Property<int>("IdSolicitacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitacao"));

                    b.Property<DateTime>("DataNecessidadeEmObra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacaoCliente")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.HasKey("IdSolicitacao");

                    b.HasIndex("IdCaixilho");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("SolicitacaoCliente");
                });

            modelBuilder.Entity("API.SIGE.Model.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<string>("NomeTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdTipoUsuario");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("API.SIGE.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("IdCargo")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Model.Anexo", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Medicao", "Medicao")
                        .WithMany()
                        .HasForeignKey("IdMedicao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Model.ProducaoFamilia", "ProducaoFamilia")
                        .WithMany()
                        .HasForeignKey("IdProducaoFamilia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Medicao");

                    b.Navigation("ProducaoFamilia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Model.Caixilho", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("API.SIGE.Model.Cargo", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("API.SIGE.Model.FamiliaCaixilho", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Obra", "Obra")
                        .WithMany("FamiliasCaixilho")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("API.SIGE.Model.Medicao", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("API.SIGE.Model.Notificacao", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Model.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Obra");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("API.SIGE.Model.Obra", b =>
                {
                    b.HasOne("API.SIGE.Model.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Model.ProducaoFamilia", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("API.SIGE.Model.SolicitacaoCliente", b =>
                {
                    b.HasOne("API.SIGE.Model.Caixilho", "Caixilho")
                        .WithMany()
                        .HasForeignKey("IdCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caixilho");

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("API.SIGE.Model.TipoUsuario", b =>
                {
                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("API.SIGE.Model.Usuario", b =>
                {
                    b.HasOne("API.SIGE.Model.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.SIGE.Model.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Empresa");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("API.SIGE.Model.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API.SIGE.Model.Obra", b =>
                {
                    b.Navigation("FamiliasCaixilho");
                });
#pragma warning restore 612, 618
        }
    }
}
